import type { NextPage } from "next";
import Head from "next/head";

import CubeButton from '@/components/button/CubeButton'
import OLLCubes from '@/data/OLLCubes'
import PLLCubes from '@/data/PLLCubes'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full w-full grid place-content-center grid-cols-[10rem_10rem] grid-rows-[10rem] gap-6 mx-auto">
        <CubeButton href="/oll" text="OLL">
          <CubeButton.OLLCube {...OLLCubes['Awkward Shapes']['OLL 29']}/>
        </CubeButton>
        <CubeButton href="/pll" text="PLL">
          <CubeButton.PLLCube {...PLLCubes['Adjacent Corner Swap']['Rb']}/>
        </CubeButton>
      </main>
    </>
  );
};

export default Home;
